image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup and Run Tests
    init: mvn clean install
    command: mvn test

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
